/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Principal;

import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class Form_saque extends javax.swing.JFrame {

    /**
     * Creates new form Form_saque
     */
    public Form_saque() {
        initComponents();
        ConexaoBD c = new ConexaoBD();
        c.preencherTabelaSaque();       
        estadoTxt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        txtPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente3 = new javax.swing.JTable();
        javax.swing.JLabel Depositos = new javax.swing.JLabel();
        lbl_nome2 = new javax.swing.JLabel();
        txt_nome3 = new javax.swing.JTextField();
        lbl_nroConta = new javax.swing.JLabel();
        txt_nroConta3 = new javax.swing.JTextField();
        lbl_saldo2 = new javax.swing.JLabel();
        txt_saldo3 = new javax.swing.JTextField();
        lbl_qntDeposito = new javax.swing.JLabel();
        txt_saque = new javax.swing.JTextField();
        btn_sacar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_nroConta1 = new javax.swing.JLabel();
        txt_limite = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saques");
        setResizable(false);

        label1.setName(""); // NOI18N
        label1.setText("Procurar");

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyTyped(evt);
            }
        });

        jTableCliente3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCliente3.setToolTipText("");
        jTableCliente3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCliente3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCliente3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCliente3);

        Depositos.setFont(Depositos.getFont().deriveFont(Depositos.getFont().getStyle() | java.awt.Font.BOLD, Depositos.getFont().getSize()+4));
        Depositos.setText("Saques");

        lbl_nome2.setText("Nome");

        lbl_nroConta.setText("Numero da conta");

        lbl_saldo2.setText("Saldo Atual");

        txt_saldo3.setText("0");

        lbl_qntDeposito.setText("Quantia do Saque");

        txt_saque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saqueActionPerformed(evt);
            }
        });

        btn_sacar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sacar.setText("SACAR");
        btn_sacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sacarActionPerformed(evt);
            }
        });

        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_nroConta1.setText("Limite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nome3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_qntDeposito)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_saque))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_saldo2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_nroConta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_nroConta3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_nroConta1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_limite, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(btn_sacar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Depositos))
                .addContainerGap(81, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Depositos)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome2)
                    .addComponent(txt_nome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nroConta)
                    .addComponent(txt_nroConta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_saldo2)
                    .addComponent(lbl_nroConta1)
                    .addComponent(txt_limite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_qntDeposito)
                    .addComponent(txt_saque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sacar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        ConexaoBD c = new ConexaoBD();
        c.preencherTabelaSaque();
    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        ConexaoBD c = new ConexaoBD();
        c.preencherTabelaSaque();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void txtPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyTyped
        ConexaoBD c = new ConexaoBD();
        c.preencherTabelaSaque();
    }//GEN-LAST:event_txtPesquisarKeyTyped

    private void jTableCliente3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCliente3MouseClicked
        int linhaSelecionada = jTableCliente3.getSelectedRow();

        txt_nome3.setText(jTableCliente3.getValueAt(linhaSelecionada, 1).toString());
        txt_nroConta3.setText(jTableCliente3.getValueAt(linhaSelecionada, 4).toString());
        txt_saldo3.setText(jTableCliente3.getValueAt(linhaSelecionada, 5).toString());
        txt_limite.setText(jTableCliente3.getValueAt(linhaSelecionada, 6).toString());

    }//GEN-LAST:event_jTableCliente3MouseClicked

    private void txt_saqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_saqueActionPerformed

    private void btn_sacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sacarActionPerformed
        ConexaoBD c = new ConexaoBD();
        if((Double.parseDouble(txt_saque.getText())) < (Double.parseDouble(txt_limite.getText()))){
        double sub = (Double.parseDouble(txt_saldo3.getText()) - (Double.parseDouble(txt_saque.getText())));
        c.Saque(sub ,Integer.parseInt(txt_nroConta3.getText()));
        txt_saque.setText(null);
        c.preencherTabelaSaque();
        txt_nome3.setText(null);
        txt_saldo3.setText(null);
        txt_nroConta3.setText(null);
        txt_limite.setText(null);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nao pode ser realizado um saque maior que seu limite","Aviso!",JOptionPane.WARNING_MESSAGE);
            txt_saque.setText(null);
        }
    }//GEN-LAST:event_btn_sacarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
     public void estadoTxt(){
        txt_nome3.setEnabled(false);
        txt_nroConta3.setEnabled(false);
        txt_saldo3.setEnabled(false);
        txt_limite.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_saque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_saque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_saque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_saque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_saque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sacar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    static javax.swing.JTable jTableCliente3;
    private java.awt.Label label1;
    private javax.swing.JLabel lbl_nome2;
    private javax.swing.JLabel lbl_nroConta;
    private javax.swing.JLabel lbl_nroConta1;
    private javax.swing.JLabel lbl_qntDeposito;
    private javax.swing.JLabel lbl_saldo2;
    static javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txt_limite;
    private javax.swing.JTextField txt_nome3;
    private javax.swing.JTextField txt_nroConta3;
    private javax.swing.JTextField txt_saldo3;
    private javax.swing.JTextField txt_saque;
    // End of variables declaration//GEN-END:variables
}
